name: Update the list of apps in APPS.md
  
on:
  push:
    branches: "master"
    paths: "02-extra/packages/*"

  workflow_dispatch:
  
permissions:
  contents: write 

jobs:
  update_app_list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build the new list
        run: |
          OUTPUT_LIST="## Apps available in this repository:\n\n<br>\n\n"
          OUTPUT_LIST+="| Package Name | Install Source | Description |\n"
          OUTPUT_LIST+="| --- | --- | --- |\n"
          mapfile -s 1 -t ALL_APPS < 02-extra/manifest
          for APP in "${ALL_APPS[@]}"; do
            unset WEBSITE METHOD SUMMARY
            if ! [[ ${APP} =~ ^# ]]; then
              WEBSITE=$(grep -o -P -m 1 "WEBSITE=\"\K[^\"]*(?=\")" "02-extra/packages/${APP}")
              SUMMARY=$(grep -o -P -m 1 "SUMMARY=\"\K[^\"]*(?=\")" "02-extra/packages/${APP}")
              if grep -q "get_github_releases" "02-extra/packages/${APP}"; then 
                METHOD="Github"
              elif grep -q "get_gitlab_releases" "02-extra/packages/${APP}"; then 
                METHOD="Gitlab"
              elif grep -q "APT_REPO_URL=" "02-extra/packages/${APP}"; then 
                METHOD="Apt Repo"
              elif grep -q "PPA=" "02-extra/packages/${APP}"; then 
                METHOD="PPA"
              else 
                METHOD="Website"
              fi
            OUTPUT_LIST+="| [\`${APP}\`](${WEBSITE}) | ${METHOD} | ${SUMMARY} |\n"
            fi
          done
          echo -e "${OUTPUT_LIST}" > APPS.md

      - name: Commit the change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add APPS.md
          git commit -m "chore: auto update APPS.md"
          git push
          
          
